-- Paises
INSERT INTO public.paises (codigo, nombre) VALUES('COL', 'Colombia');
INSERT INTO public.paises (codigo, nombre) VALUES('ARG', 'Argentina');
INSERT INTO public.paises (codigo, nombre) VALUES('VEN', 'Venezuela');
INSERT INTO public.paises (codigo, nombre) VALUES('ECU', 'Ecuador');
INSERT INTO public.paises (codigo, nombre) VALUES('URU', 'Uruguay');
INSERT INTO public.paises (codigo, nombre) VALUES('PAR', 'Paraguay');
INSERT INTO public.paises (codigo, nombre) VALUES('CHI', 'Chile');
INSERT INTO public.paises (codigo, nombre) VALUES('BRA', 'Brasil');
INSERT INTO public.paises (codigo, nombre) VALUES('PER', 'Perú');
INSERT INTO public.paises (codigo, nombre) VALUES('BOL', 'Bolivia');
INSERT INTO public.paises (codigo, nombre) VALUES('USA', 'Estados Unidos');

-- Ciudades
INSERT INTO public.ciudades(idpais, nombre, descripcion) VALUES (1, 'Santiago de Cali', 'Cali');

-- Aviones
INSERT INTO public.aviones (nombre, descripcion, referencia, tipo, capacidad) 
VALUES('Airbus A320', 'Airbus A320', 'Airbus A320', 'COMERCIAL', 180);
INSERT INTO public.aviones (nombre, descripcion, referencia, tipo, capacidad) 
VALUES('Airbus A340', 'Airbus A340', 'Airbus A340', 'COMERCIAL', 180);
INSERT INTO public.aviones (nombre, descripcion, referencia, tipo, capacidad) 
VALUES('Boeing 737', 'Boeing 737', 'Boeing 737', 'COMERCIAL', 180);
INSERT INTO public.aviones (nombre, descripcion, referencia, tipo, capacidad) 
VALUES('Boeing 777', 'Boeing 777', 'Boeing 777', 'COMERCIAL', 180);
INSERT INTO public.aviones (nombre, descripcion, referencia, tipo, capacidad) 
VALUES('Boeing 747', 'Boeing 747', 'Boeing 747', 'COMERCIAL', 180);

-- Asientos
INSERT INTO public.asientos(fila, silla) VALUES ('1','A');
INSERT INTO public.asientos(fila, silla) VALUES ('1','B');
INSERT INTO public.asientos(fila, silla) VALUES ('1','C');
INSERT INTO public.asientos(fila, silla) VALUES ('1','D');
INSERT INTO public.asientos(fila, silla) VALUES ('1','E');
INSERT INTO public.asientos(fila, silla) VALUES ('1','F');
INSERT INTO public.asientos(fila, silla) VALUES ('2','A');
INSERT INTO public.asientos(fila, silla) VALUES ('2','B');
INSERT INTO public.asientos(fila, silla) VALUES ('2','C');
INSERT INTO public.asientos(fila, silla) VALUES ('2','D');
INSERT INTO public.asientos(fila, silla) VALUES ('2','E');
INSERT INTO public.asientos(fila, silla) VALUES ('2','F');
INSERT INTO public.asientos(fila, silla) VALUES ('3','A');
INSERT INTO public.asientos(fila, silla) VALUES ('3','B');
INSERT INTO public.asientos(fila, silla) VALUES ('3','C');
INSERT INTO public.asientos(fila, silla) VALUES ('3','D');
INSERT INTO public.asientos(fila, silla) VALUES ('3','E');
INSERT INTO public.asientos(fila, silla) VALUES ('3','F');
INSERT INTO public.asientos(fila, silla) VALUES ('4','A');
INSERT INTO public.asientos(fila, silla) VALUES ('4','B');
INSERT INTO public.asientos(fila, silla) VALUES ('4','C');
INSERT INTO public.asientos(fila, silla) VALUES ('4','D');
INSERT INTO public.asientos(fila, silla) VALUES ('4','E');
INSERT INTO public.asientos(fila, silla) VALUES ('4','F');
INSERT INTO public.asientos(fila, silla) VALUES ('5','A');
INSERT INTO public.asientos(fila, silla) VALUES ('5','B');
INSERT INTO public.asientos(fila, silla) VALUES ('5','C');
INSERT INTO public.asientos(fila, silla) VALUES ('5','D');
INSERT INTO public.asientos(fila, silla) VALUES ('5','E');
INSERT INTO public.asientos(fila, silla) VALUES ('5','F');
INSERT INTO public.asientos(fila, silla) VALUES ('6','A');
INSERT INTO public.asientos(fila, silla) VALUES ('6','B');
INSERT INTO public.asientos(fila, silla) VALUES ('6','C');
INSERT INTO public.asientos(fila, silla) VALUES ('6','D');
INSERT INTO public.asientos(fila, silla) VALUES ('6','E');
INSERT INTO public.asientos(fila, silla) VALUES ('6','F');
INSERT INTO public.asientos(fila, silla) VALUES ('7','A');
INSERT INTO public.asientos(fila, silla) VALUES ('7','B');
INSERT INTO public.asientos(fila, silla) VALUES ('7','C');
INSERT INTO public.asientos(fila, silla) VALUES ('7','D');
INSERT INTO public.asientos(fila, silla) VALUES ('7','E');
INSERT INTO public.asientos(fila, silla) VALUES ('7','F');
INSERT INTO public.asientos(fila, silla) VALUES ('8','A');
INSERT INTO public.asientos(fila, silla) VALUES ('8','B');
INSERT INTO public.asientos(fila, silla) VALUES ('8','C');
INSERT INTO public.asientos(fila, silla) VALUES ('8','D');
INSERT INTO public.asientos(fila, silla) VALUES ('8','E');
INSERT INTO public.asientos(fila, silla) VALUES ('8','F');
INSERT INTO public.asientos(fila, silla) VALUES ('9','A');
INSERT INTO public.asientos(fila, silla) VALUES ('9','B');
INSERT INTO public.asientos(fila, silla) VALUES ('9','C');
INSERT INTO public.asientos(fila, silla) VALUES ('9','D');
INSERT INTO public.asientos(fila, silla) VALUES ('9','E');
INSERT INTO public.asientos(fila, silla) VALUES ('9','F');
INSERT INTO public.asientos(fila, silla) VALUES ('10','A');
INSERT INTO public.asientos(fila, silla) VALUES ('10','B');
INSERT INTO public.asientos(fila, silla) VALUES ('10','C');
INSERT INTO public.asientos(fila, silla) VALUES ('10','D');
INSERT INTO public.asientos(fila, silla) VALUES ('10','E');
INSERT INTO public.asientos(fila, silla) VALUES ('10','F');
INSERT INTO public.asientos(fila, silla) VALUES ('11','A');
INSERT INTO public.asientos(fila, silla) VALUES ('11','B');
INSERT INTO public.asientos(fila, silla) VALUES ('11','C');
INSERT INTO public.asientos(fila, silla) VALUES ('11','D');
INSERT INTO public.asientos(fila, silla) VALUES ('11','E');
INSERT INTO public.asientos(fila, silla) VALUES ('11','F');
INSERT INTO public.asientos(fila, silla) VALUES ('12','A');
INSERT INTO public.asientos(fila, silla) VALUES ('12','B');
INSERT INTO public.asientos(fila, silla) VALUES ('12','C');
INSERT INTO public.asientos(fila, silla) VALUES ('12','D');
INSERT INTO public.asientos(fila, silla) VALUES ('12','E');
INSERT INTO public.asientos(fila, silla) VALUES ('12','F');
INSERT INTO public.asientos(fila, silla) VALUES ('13','A');
INSERT INTO public.asientos(fila, silla) VALUES ('13','B');
INSERT INTO public.asientos(fila, silla) VALUES ('13','C');
INSERT INTO public.asientos(fila, silla) VALUES ('13','D');
INSERT INTO public.asientos(fila, silla) VALUES ('13','E');
INSERT INTO public.asientos(fila, silla) VALUES ('13','F');
INSERT INTO public.asientos(fila, silla) VALUES ('14','A');
INSERT INTO public.asientos(fila, silla) VALUES ('14','B');
INSERT INTO public.asientos(fila, silla) VALUES ('14','C');
INSERT INTO public.asientos(fila, silla) VALUES ('14','D');
INSERT INTO public.asientos(fila, silla) VALUES ('14','E');
INSERT INTO public.asientos(fila, silla) VALUES ('14','F');
INSERT INTO public.asientos(fila, silla) VALUES ('15','A');
INSERT INTO public.asientos(fila, silla) VALUES ('15','B');
INSERT INTO public.asientos(fila, silla) VALUES ('15','C');
INSERT INTO public.asientos(fila, silla) VALUES ('15','D');
INSERT INTO public.asientos(fila, silla) VALUES ('15','E');
INSERT INTO public.asientos(fila, silla) VALUES ('15','F');
INSERT INTO public.asientos(fila, silla) VALUES ('16','A');
INSERT INTO public.asientos(fila, silla) VALUES ('16','B');
INSERT INTO public.asientos(fila, silla) VALUES ('16','C');
INSERT INTO public.asientos(fila, silla) VALUES ('16','D');
INSERT INTO public.asientos(fila, silla) VALUES ('16','E');
INSERT INTO public.asientos(fila, silla) VALUES ('16','F');
INSERT INTO public.asientos(fila, silla) VALUES ('17','A');
INSERT INTO public.asientos(fila, silla) VALUES ('17','B');
INSERT INTO public.asientos(fila, silla) VALUES ('17','C');
INSERT INTO public.asientos(fila, silla) VALUES ('17','D');
INSERT INTO public.asientos(fila, silla) VALUES ('17','E');
INSERT INTO public.asientos(fila, silla) VALUES ('17','F');
INSERT INTO public.asientos(fila, silla) VALUES ('18','A');
INSERT INTO public.asientos(fila, silla) VALUES ('18','B');
INSERT INTO public.asientos(fila, silla) VALUES ('18','C');
INSERT INTO public.asientos(fila, silla) VALUES ('18','D');
INSERT INTO public.asientos(fila, silla) VALUES ('18','E');
INSERT INTO public.asientos(fila, silla) VALUES ('18','F');
INSERT INTO public.asientos(fila, silla) VALUES ('19','A');
INSERT INTO public.asientos(fila, silla) VALUES ('19','B');
INSERT INTO public.asientos(fila, silla) VALUES ('19','C');
INSERT INTO public.asientos(fila, silla) VALUES ('19','D');
INSERT INTO public.asientos(fila, silla) VALUES ('19','E');
INSERT INTO public.asientos(fila, silla) VALUES ('19','F');
INSERT INTO public.asientos(fila, silla) VALUES ('20','A');
INSERT INTO public.asientos(fila, silla) VALUES ('20','B');
INSERT INTO public.asientos(fila, silla) VALUES ('20','C');
INSERT INTO public.asientos(fila, silla) VALUES ('20','D');
INSERT INTO public.asientos(fila, silla) VALUES ('20','E');
INSERT INTO public.asientos(fila, silla) VALUES ('20','F');
INSERT INTO public.asientos(fila, silla) VALUES ('21','A');
INSERT INTO public.asientos(fila, silla) VALUES ('21','B');
INSERT INTO public.asientos(fila, silla) VALUES ('21','C');
INSERT INTO public.asientos(fila, silla) VALUES ('21','D');
INSERT INTO public.asientos(fila, silla) VALUES ('21','E');
INSERT INTO public.asientos(fila, silla) VALUES ('21','F');
INSERT INTO public.asientos(fila, silla) VALUES ('22','A');
INSERT INTO public.asientos(fila, silla) VALUES ('22','B');
INSERT INTO public.asientos(fila, silla) VALUES ('22','C');
INSERT INTO public.asientos(fila, silla) VALUES ('22','D');
INSERT INTO public.asientos(fila, silla) VALUES ('22','E');
INSERT INTO public.asientos(fila, silla) VALUES ('22','F');
INSERT INTO public.asientos(fila, silla) VALUES ('23','A');
INSERT INTO public.asientos(fila, silla) VALUES ('23','B');
INSERT INTO public.asientos(fila, silla) VALUES ('23','C');
INSERT INTO public.asientos(fila, silla) VALUES ('23','D');
INSERT INTO public.asientos(fila, silla) VALUES ('23','E');
INSERT INTO public.asientos(fila, silla) VALUES ('23','F');
INSERT INTO public.asientos(fila, silla) VALUES ('24','A');
INSERT INTO public.asientos(fila, silla) VALUES ('24','B');
INSERT INTO public.asientos(fila, silla) VALUES ('24','C');
INSERT INTO public.asientos(fila, silla) VALUES ('24','D');
INSERT INTO public.asientos(fila, silla) VALUES ('24','E');
INSERT INTO public.asientos(fila, silla) VALUES ('24','F');
INSERT INTO public.asientos(fila, silla) VALUES ('25','A');
INSERT INTO public.asientos(fila, silla) VALUES ('25','B');
INSERT INTO public.asientos(fila, silla) VALUES ('25','C');
INSERT INTO public.asientos(fila, silla) VALUES ('25','D');
INSERT INTO public.asientos(fila, silla) VALUES ('25','E');
INSERT INTO public.asientos(fila, silla) VALUES ('25','F');
INSERT INTO public.asientos(fila, silla) VALUES ('26','A');
INSERT INTO public.asientos(fila, silla) VALUES ('26','B');
INSERT INTO public.asientos(fila, silla) VALUES ('26','C');
INSERT INTO public.asientos(fila, silla) VALUES ('26','D');
INSERT INTO public.asientos(fila, silla) VALUES ('26','E');
INSERT INTO public.asientos(fila, silla) VALUES ('26','F');
INSERT INTO public.asientos(fila, silla) VALUES ('27','A');
INSERT INTO public.asientos(fila, silla) VALUES ('27','B');
INSERT INTO public.asientos(fila, silla) VALUES ('27','C');
INSERT INTO public.asientos(fila, silla) VALUES ('27','D');
INSERT INTO public.asientos(fila, silla) VALUES ('27','E');
INSERT INTO public.asientos(fila, silla) VALUES ('27','F');
INSERT INTO public.asientos(fila, silla) VALUES ('28','A');
INSERT INTO public.asientos(fila, silla) VALUES ('28','B');
INSERT INTO public.asientos(fila, silla) VALUES ('28','C');
INSERT INTO public.asientos(fila, silla) VALUES ('28','D');
INSERT INTO public.asientos(fila, silla) VALUES ('28','E');
INSERT INTO public.asientos(fila, silla) VALUES ('28','F');
INSERT INTO public.asientos(fila, silla) VALUES ('29','A');
INSERT INTO public.asientos(fila, silla) VALUES ('29','B');
INSERT INTO public.asientos(fila, silla) VALUES ('29','C');
INSERT INTO public.asientos(fila, silla) VALUES ('29','D');
INSERT INTO public.asientos(fila, silla) VALUES ('29','E');
INSERT INTO public.asientos(fila, silla) VALUES ('29','F');
INSERT INTO public.asientos(fila, silla) VALUES ('30','A');
INSERT INTO public.asientos(fila, silla) VALUES ('30','B');
INSERT INTO public.asientos(fila, silla) VALUES ('30','C');
INSERT INTO public.asientos(fila, silla) VALUES ('30','D');
INSERT INTO public.asientos(fila, silla) VALUES ('30','E');
INSERT INTO public.asientos(fila, silla) VALUES ('30','F');
INSERT INTO public.asientos(fila, silla) VALUES ('31','A');
INSERT INTO public.asientos(fila, silla) VALUES ('31','B');
INSERT INTO public.asientos(fila, silla) VALUES ('31','C');
INSERT INTO public.asientos(fila, silla) VALUES ('31','D');
INSERT INTO public.asientos(fila, silla) VALUES ('31','E');
INSERT INTO public.asientos(fila, silla) VALUES ('31','F');
INSERT INTO public.asientos(fila, silla) VALUES ('32','A');
INSERT INTO public.asientos(fila, silla) VALUES ('32','B');
INSERT INTO public.asientos(fila, silla) VALUES ('32','C');
INSERT INTO public.asientos(fila, silla) VALUES ('32','D');
INSERT INTO public.asientos(fila, silla) VALUES ('32','E');
INSERT INTO public.asientos(fila, silla) VALUES ('32','F');

-- AsientosXAvion
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,1,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,2,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,3,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,4,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,5,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,6,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,7,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,8,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,9,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,10,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,11,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,12,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,13,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,14,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,15,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,16,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,17,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,18,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,19,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,20,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,21,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,22,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,23,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,24,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,25,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,26,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,27,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,28,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,29,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,30,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,31,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,32,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,33,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,34,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,35,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,36,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,37,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,38,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,39,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,40,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,41,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,42,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,43,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,44,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,45,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,46,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,47,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,48,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,49,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,50,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,51,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,52,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,53,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,54,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,55,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,56,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,57,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,58,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,59,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,60,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,61,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,62,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,63,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,64,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,65,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,66,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,67,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,68,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,69,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,70,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,71,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,72,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,73,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,74,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,75,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,76,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,77,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,78,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,79,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,80,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,81,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,82,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,83,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,84,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,85,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,86,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,87,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,88,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,89,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,90,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,91,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,92,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,93,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,94,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,95,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,96,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,97,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,98,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,99,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,100,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,101,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,102,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,103,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,104,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,105,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,106,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,107,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,108,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,109,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,110,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,111,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,112,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,113,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,114,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,115,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,116,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,117,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,118,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,119,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,120,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,121,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,122,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,123,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,124,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,125,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,126,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,127,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,128,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,129,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,130,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,131,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,132,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,133,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,134,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,135,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,136,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,137,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,138,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,139,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,140,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,141,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,142,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,143,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,144,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,145,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,146,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,147,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,148,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,149,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,150,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,151,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,152,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,153,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,154,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,155,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,156,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,157,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,158,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,159,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,160,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,161,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,162,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,163,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,164,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,165,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,166,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,167,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,168,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,169,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,170,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,171,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,172,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,173,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,174,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,175,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,176,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,177,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,178,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,179,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,180,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,181,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,182,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,183,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,184,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,185,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,186,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,187,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,188,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,189,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,190,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,191,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (1,192,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,1,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,2,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,3,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,4,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,5,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,6,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,7,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,8,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,9,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,10,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,11,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,12,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,13,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,14,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,15,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,16,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,17,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,18,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,19,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,20,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,21,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,22,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,23,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,24,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,25,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,26,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,27,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,28,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,29,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,30,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,31,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,32,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,33,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,34,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,35,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,36,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,37,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,38,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,39,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,40,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,41,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,42,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,43,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,44,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,45,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,46,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,47,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,48,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,49,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,50,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,51,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,52,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,53,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,54,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,55,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,56,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,57,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,58,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,59,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,60,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,61,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,62,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,63,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,64,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,65,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,66,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,67,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,68,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,69,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,70,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,71,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,72,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,73,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,74,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,75,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,76,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,77,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,78,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,79,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,80,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,81,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,82,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,83,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,84,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,85,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,86,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,87,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,88,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,89,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,90,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,91,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,92,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,93,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,94,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,95,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,96,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,97,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,98,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,99,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,100,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,101,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,102,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,103,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,104,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,105,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,106,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,107,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,108,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,109,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,110,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,111,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,112,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,113,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,114,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,115,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,116,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,117,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,118,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,119,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,120,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,121,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,122,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,123,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,124,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,125,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,126,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,127,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,128,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,129,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,130,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,131,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,132,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,133,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,134,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,135,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,136,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,137,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,138,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,139,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,140,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,141,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,142,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,143,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,144,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,145,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,146,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,147,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,148,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,149,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,150,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,151,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,152,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,153,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,154,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,155,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,156,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,157,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,158,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,159,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,160,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,161,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,162,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,163,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,164,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,165,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,166,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,167,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,168,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,169,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,170,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,171,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,172,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,173,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,174,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,175,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,176,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,177,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,178,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,179,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,180,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,181,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,182,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,183,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,184,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,185,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,186,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,187,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,188,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,189,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,190,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,191,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (2,192,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,1,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,2,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,3,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,4,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,5,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,6,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,7,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,8,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,9,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,10,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,11,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,12,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,13,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,14,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,15,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,16,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,17,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,18,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,19,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,20,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,21,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,22,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,23,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,24,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,25,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,26,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,27,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,28,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,29,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,30,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,31,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,32,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,33,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,34,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,35,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,36,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,37,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,38,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,39,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,40,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,41,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,42,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,43,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,44,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,45,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,46,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,47,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,48,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,49,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,50,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,51,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,52,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,53,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,54,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,55,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,56,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,57,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,58,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,59,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,60,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,61,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,62,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,63,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,64,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,65,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,66,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,67,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,68,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,69,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,70,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,71,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,72,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,73,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,74,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,75,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,76,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,77,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,78,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,79,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,80,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,81,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,82,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,83,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,84,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,85,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,86,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,87,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,88,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,89,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,90,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,91,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,92,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,93,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,94,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,95,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,96,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,97,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,98,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,99,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,100,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,101,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,102,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,103,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,104,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,105,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,106,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,107,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,108,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,109,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,110,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,111,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,112,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,113,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,114,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,115,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,116,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,117,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,118,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,119,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,120,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,121,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,122,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,123,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,124,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,125,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,126,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,127,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,128,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,129,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,130,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,131,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,132,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,133,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,134,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,135,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,136,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,137,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,138,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,139,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,140,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,141,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,142,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,143,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,144,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,145,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,146,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,147,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,148,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,149,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,150,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,151,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,152,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,153,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,154,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,155,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,156,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,157,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,158,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,159,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,160,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,161,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,162,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,163,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,164,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,165,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,166,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,167,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,168,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,169,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,170,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,171,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,172,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,173,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,174,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,175,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,176,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,177,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,178,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,179,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,180,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,181,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,182,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,183,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,184,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,185,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,186,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,187,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,188,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,189,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,190,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,191,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (3,192,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,1,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,2,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,3,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,4,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,5,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,6,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,7,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,8,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,9,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,10,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,11,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,12,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,13,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,14,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,15,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,16,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,17,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,18,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,19,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,20,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,21,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,22,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,23,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,24,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,25,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,26,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,27,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,28,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,29,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,30,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,31,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,32,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,33,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,34,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,35,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,36,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,37,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,38,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,39,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,40,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,41,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,42,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,43,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,44,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,45,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,46,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,47,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,48,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,49,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,50,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,51,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,52,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,53,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,54,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,55,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,56,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,57,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,58,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,59,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,60,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,61,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,62,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,63,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,64,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,65,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,66,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,67,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,68,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,69,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,70,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,71,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,72,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,73,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,74,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,75,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,76,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,77,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,78,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,79,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,80,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,81,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,82,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,83,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,84,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,85,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,86,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,87,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,88,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,89,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,90,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,91,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,92,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,93,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,94,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,95,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,96,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,97,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,98,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,99,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,100,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,101,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,102,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,103,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,104,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,105,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,106,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,107,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,108,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,109,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,110,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,111,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,112,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,113,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,114,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,115,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,116,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,117,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,118,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,119,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,120,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,121,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,122,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,123,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,124,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,125,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,126,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,127,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,128,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,129,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,130,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,131,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,132,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,133,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,134,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,135,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,136,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,137,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,138,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,139,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,140,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,141,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,142,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,143,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,144,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,145,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,146,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,147,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,148,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,149,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,150,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,151,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,152,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,153,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,154,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,155,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,156,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,157,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,158,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,159,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,160,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,161,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,162,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,163,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,164,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,165,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,166,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,167,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,168,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,169,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,170,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,171,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,172,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,173,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,174,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,175,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,176,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,177,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,178,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,179,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,180,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,181,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,182,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,183,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,184,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,185,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,186,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,187,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,188,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,189,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,190,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,191,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (4,192,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,1,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,2,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,3,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,4,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,5,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,6,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,7,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,8,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,9,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,10,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,11,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,12,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,13,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,14,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,15,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,16,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,17,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,18,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,19,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,20,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,21,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,22,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,23,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,24,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,25,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,26,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,27,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,28,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,29,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,30,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,31,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,32,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,33,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,34,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,35,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,36,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,37,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,38,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,39,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,40,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,41,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,42,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,43,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,44,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,45,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,46,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,47,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,48,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,49,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,50,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,51,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,52,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,53,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,54,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,55,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,56,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,57,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,58,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,59,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,60,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,61,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,62,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,63,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,64,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,65,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,66,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,67,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,68,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,69,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,70,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,71,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,72,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,73,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,74,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,75,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,76,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,77,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,78,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,79,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,80,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,81,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,82,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,83,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,84,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,85,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,86,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,87,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,88,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,89,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,90,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,91,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,92,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,93,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,94,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,95,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,96,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,97,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,98,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,99,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,100,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,101,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,102,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,103,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,104,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,105,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,106,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,107,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,108,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,109,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,110,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,111,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,112,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,113,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,114,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,115,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,116,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,117,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,118,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,119,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,120,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,121,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,122,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,123,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,124,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,125,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,126,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,127,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,128,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,129,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,130,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,131,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,132,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,133,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,134,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,135,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,136,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,137,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,138,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,139,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,140,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,141,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,142,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,143,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,144,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,145,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,146,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,147,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,148,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,149,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,150,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,151,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,152,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,153,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,154,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,155,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,156,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,157,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,158,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,159,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,160,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,161,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,162,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,163,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,164,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,165,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,166,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,167,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,168,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,169,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,170,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,171,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,172,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,173,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,174,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,175,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,176,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,177,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,178,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,179,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,180,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,181,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,182,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,183,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,184,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,185,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,186,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,187,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,188,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,189,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,190,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,191,'A');
INSERT INTO public.asientosxavion(idaviones, idasientos, estado) VALUES (5,192,'A');
